# Title

* **Difficulty level**: easy
* **Time need to lean**: 10 minutes or less
* **Key points**:
  * a

## Ruby

Basic data types recognised in Ruby are similar with Python's data types and there is a one-to-one correspondence for these types.

The convertion of datatype from SoS to Ruby (e.g. `%get` from Ruby) is as followings:

  
  | Python  |  condition |   Ruby |
  | --- | --- |---|
  | `None` | |    `nil` |
  | `boolean` |   | `TrueClass or FalseClass` |
  | `integer` |  |  `Integer` |
  | `float` |  |  `Float` |
  | `complex` |  |  `Complex` |
  | `str` |  | `String` |
  | Sequence (`list`, `tuple`, ...) |  |  `Array` |
  | `set` |  |  `Set` |
  | `dict` |  |  `Hash` |
  | `range` |  |  `Range` |
  | `numpy.ndarray` |  | `Array` |
  | `numpy.matrix` |  | `NMatrix` |
  | `pandas.Series` |  | `Hash` |
  | `pandas.DataFrame` |  | `Daru::DataFrame` |

  Python objects in other datatypes are transferred as string `"Unsupported datatype"`. Please [let us know](https://github.com/vatlab/sos-ruby/issues) if there is a natural corresponding data type in Ruby to convert this data type.

Conversion of datatypes from Ruby to SoS (`%get var --from Ruby` from SoS) follows the following rules:

  | Ruby  |  condition |   Python |
  | --- | ---| ---|
  | `nil` |     |  `None` |
  | `Float::NAN` |     |  `numpy.nan` |
  | `TrueClass or FalseClass` |     |  `boolean` |
  | `Integer` |     |   `integer` |
  | `String` |     |  `str` |
  | `Complex` |     |  `complex` |
  | `Float` |     |  `float` |
  | `Array` |     |   `numpy.ndarray` |
  | `Range` |     |   `range` |
  | `Set` |      | `set` |
  | `Hash` |      |  `dict` |
  | `NMatrix` |   |  `numpy.matrix` |
  | `Array` |   |  `numpy.ndarray` |
  | `Daru::DataFrame` |      |  `pandas.DataFrame` |
  Ruby objects in other datatypes are transferred as string `"Unsupported datatype"`.

For example, the scalar data is converted from SoS to Ruby as follows:

In [1]:
null_var = None
num_var = 123
logic_var = True
char_var = '1"23'
comp_var = 1+2j

In [2]:
%get null_var num_var logic_var char_var comp_var
puts [null_var, num_var, logic_var, char_var, comp_var]

[nil, 123, true, "1\"23", (1.0+2.0i)]

Ruby supports DataFrame from its daru (Data Analysis in RUby) library so you will need to install this library before using the Ruby kernel. For example, a R dataframe is transfered as Daru::DataFrame to Ruby.

In [3]:
%get mtcars --from R
mtcars

Loading required package: feather

#<Daru::DataFrame(32x11)>
                   mpg        cyl       disp         hp       drat         wt       qsec         vs         am       gear       carb
  Mazda RX4       21.0        6.0      160.0      110.0        3.9       2.62      16.46        0.0        1.0        4.0        4.0
 Mazda RX4        21.0        6.0      160.0      110.0        3.9      2.875      17.02        0.0        1.0        4.0        4.0
 Datsun 710       22.8        4.0      108.0       93.0       3.85       2.32      18.61        1.0        1.0        4.0        1.0
 Hornet 4 D       21.4        6.0      258.0      110.0       3.08      3.215      19.44        1.0        0.0        3.0        1.0
 Hornet Spo       18.7        8.0      360.0      175.0       3.15       3.44      17.02        0.0        0.0        3.0        2.0
    Valiant       18.1        6.0      225.0      105.0       2.76       3.46      20.22        1.0        0.0        3.0        1.0
 Duster 360       14.3        8.0      360.0      245.0       3.21       3.57      15.84        0.0        0.0        3.0        4.0
  Merc 240D       24.4        4.0      146.7       62.0       3.69       3.19       20.0        1.0        0.0        4.0        2.0
   Merc 230       22.8        4.0      140.8       95.0       3.92       3.15       22.9        1.0        0.0        4.0        2.0
   Merc 280       19.2        6.0      167.6      123.0       3.92       3.44       18.3        1.0        0.0        4.0        4.0
  Merc 280C       17.8        6.0      167.6      123.0       3.92       3.44       18.9        1.0        0.0        4.0        4.0
 Merc 450SE       16.4        8.0      275.8      180.0       3.07       4.07       17.4        0.0        0.0        3.0        3.0
 Merc 450SL       17.3        8.0      275.8      180.0       3.07       3.73       17.6        0.0        0.0        3.0        3.0
 Merc 450SL       15.2        8.0      275.8      180.0       3.07       3.78       18.0        0.0        0.0        3.0        3.0
 Cadillac F       10.4        8.0      472.0      205.0       2.93       5.25      17.98        0.0        0.0        3.0        4.0
        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...

Also, we choose NMatrix library in Ruby becuase its fast performance. Same as daru (Data Analysis in RUby), you will need to install nmatrix library before using the Ruby kernel.

In [4]:
mat_var = N[ [2, 3, 4], [7, 8, 9] ]

#<NMatrix:0x00007fd374374ca0 shape:[2,3] dtype:int32 stype:dense>

In [5]:
%put mat_var

'numpy.matrix([[2, 3, 4], [7, 8, 9]])'

In [6]:
mat_var

matrix([[2, 3, 4],
        [7, 8, 9]])

## Further reading

*